export type GameProject = {
  slug: string; title: string; desc: string; number: string; h1: string;
  sub: string; meta: [string, string];   bullets: string[]; note: string;
  skills: string[]; focus: string; image?: { src: string; alt: string } };

export const GAME_PROJECTS: GameProject[] = [
  {
    slug: 'duo-alphabet',
    title: 'Duo Alphabet — Sarra',
    desc: 'Duo Alphabet — Sarra portfolio project.',
    number: 'PROJECT 01',
    h1: 'Duo Alphabet',
    sub: 'Product Design · Packaging · Illustration',
    note: 'This project shows how I combine creative direction with practical design and development skills — focusing on both the visual result and the experience behind it.',
    focus: 'Product Design · Packaging · Illustration',
    meta: ['Pédaludique', 'Educational puzzle / product design'],
    bullets: ['Worked on the Duo Alphabet (casse-tête) as part of the Pédaludique educational product range.', 'Designed the product visual direction and packaging so the physical product and its presentation felt cohesive.', 'Created supporting visual elements and illustrations for the learning experience.', 'Focused on a playful, child-friendly visual language while keeping the product clear and usable.'],
    skills: ['Product Design', 'Packaging', 'Illustration', 'Educational Design'],
    image: { src: '/images/duo-alphabet.png', alt: 'Duo Alphabet educational puzzle product' },
  },
  {
    slug: 'busy-book',
    title: 'Busy Book en français — Sarra',
    desc: 'Busy Book en français — Sarra portfolio project.',
    number: 'PROJECT 02',
    h1: 'Busy Book en français',
    sub: 'Illustration · Educational Product · Visual Assets',
    note: 'This project shows how I combine creative direction with practical design and development skills — focusing on both the visual result and the experience behind it.',
    focus: 'Illustration · Educational Product · Visual Assets',
    meta: ['Pédaludique', 'French educational activity book'],
    bullets: ['Illustrated every drawing for the Busy Book en français.', 'Developed the visual assets used throughout the activities with a consistent, friendly style.', 'Balanced playful illustration with clear educational communication so the activities remain easy for children to understand.', 'Worked across multiple pages and activity types while keeping the visual language consistent.'],
    skills: ['Illustration', 'Educational Design', 'Visual Assets'],
    image: { src: '/images/busy-book.png', alt: 'Busy Book en français educational busy book' },
  },
  {
    slug: 'adam-app',
    title: 'Adam — Baby Tracking App — Sarra',
    desc: 'Adam — Baby Tracking App — Sarra portfolio project.',
    number: 'PROJECT 03',
    h1: 'Adam — Baby Tracking App',
    sub: 'UI/UX · Product Design · Visual Design',
    note: 'This project shows how I combine creative direction with practical design and development skills — focusing on both the visual result and the experience behind it.',
    focus: 'UI/UX · Product Design · Visual Design',
    meta: ['Independent Project', 'Baby-care tracking app concept'],
    bullets: ['Designed the concept and visual direction for a baby-care tracking application focused on quick everyday logging.', 'Planned and designed flows for feeding, breastfeeding, bottles, mixed feeding, sleep, wake windows, diapers, bath, health, vaccinations, growth, milestones, calendar, history, and insights.', 'Created the custom UI icon system, baby illustrations, mascot-style visuals, and supporting artwork used throughout the interface.', 'Designed a soft pastel visual system with clear hierarchy so frequent actions can be logged quickly.', 'Worked on product structure, UI screens, interaction ideas, and the overall experience rather than only individual graphics.'],
    skills: ['UI/UX', 'Product Design', 'Icon System', 'Illustration', 'Interaction Design'],
    image: { src: '/images/adam.png', alt: 'Adam baby-care tracking app concept and visual design' },
  },
  {
    slug: 'usagi',
    title: 'Usagi — Sarra',
    desc: 'Usagi — Sarra portfolio project.',
    number: 'PROJECT 04',
    h1: 'Usagi',
    sub: 'Web Design · Creative Direction · Digital Art',
    note: 'This project shows how I combine creative direction with practical design and development skills — focusing on both the visual result and the experience behind it.',
    focus: 'Web Design · Creative Direction · Digital Art',
    meta: ['Personal Creative Project', 'Portfolio / creative brand'],
    bullets: ['Designed and developed my personal creative portfolio around a playful, kawaii-inspired visual identity.', 'Combined web development with digital illustration, traditional painting, 3D work, and visual storytelling.', 'Built interactive details and animations to make the portfolio feel like a creative experience rather than a standard résumé page.', 'Use the portfolio to present both technical work and artistic projects in one cohesive visual world.'],
    skills: ['Web Design', 'Creative Direction', 'Digital Illustration', '3D', 'Front-end'],
    image: { src: '/images/usagi.png', alt: 'Usagi creative portfolio website' },
  },
  {
    slug: '3d-product-work',
    title: '3D Product Work — Sarra',
    desc: '3D Product Work — Sarra portfolio project.',
    number: 'PROJECT 05',
    h1: '3D Product Work',
    sub: '3D Modeling · Blender · Rendering',
    note: 'This project shows how I combine creative direction with practical design and development skills — focusing on both the visual result and the experience behind it.',
    focus: '3D Modeling · Blender · Rendering<br><br>Project visuals can be added here as screenshots, mockups, product photos, or renders.',
    meta: ['Freelance / Creative Work', 'Product visualization'],
    bullets: ['Created 3D models for products and creative projects using Blender.', 'Produced rendered visuals designed for product presentation and online use.', 'Worked from ideas and references to build clean, presentation-ready 3D assets.', 'Combined modeling, materials, lighting, composition, and rendering to communicate the product visually.'],
    skills: ['Blender', '3D Modeling', 'Rendering', 'Product Visualization'],
  },
  {
    slug: 'pedaludique-storefront',
    title: 'Pédaludique Storefront — Sarra',
    desc: 'Pédaludique Storefront — Sarra portfolio project.',
    number: 'PROJECT 06',
    h1: 'Pédaludique Storefront',
    sub: 'Shopify · Liquid · Front-end · E-commerce',
    note: 'This project shows how I combine creative direction with practical design and development skills — focusing on both the visual result and the experience behind it.',
    focus: 'Shopify · Liquid · Front-end · E-commerce',
    meta: ['Pédaludique · April 2024 – May 2025', 'Custom educational-toy storefront'],
    bullets: ['Customized and developed the Pédaludique Shopify storefront using the Dawn theme.', 'Worked with Liquid, HTML, CSS, JavaScript, and Shopify metafields to create and customize storefront sections and product experiences.', 'Built responsive visual details and tailored components around the brand and its educational products.', 'Combined development with product visuals, illustration, and 3D assets so the storefront and product presentation worked together as one experience.'],
    skills: ['Shopify', 'Liquid', 'Dawn Theme', 'HTML / CSS', 'JavaScript', 'Metafields'],
    image: { src: '/images/pedaludique.png', alt: 'Pédaludique Shopify storefront' },
  },
  {
    slug: 'kika-maison',
    title: 'Kika Maison — Sarra',
    desc: 'Kika Maison — Sarra portfolio project.',
    number: 'PROJECT 07',
    h1: 'Kika Maison',
    sub: 'Web Design · E-commerce · Front-end',
    note: 'This project shows how I combine creative direction with practical design and development skills — focusing on both the visual result and the experience behind it.',
    focus: 'Web Design · E-commerce · Front-end',
    meta: ['Freelance Project', 'Bedding & home-textile e-commerce storefront'],
    bullets: ['Designed and built an e-commerce storefront for Kika Maison, a bedding and home-textile business.', 'Created the product catalogue and shopping experience: collections, product pages, cart, and WhatsApp-based ordering.', 'Designed a responsive, elegant presentation built around the brand’s real product photography.', 'Handled the visual direction, layout, and front-end experience from product discovery to ordering.'],
    skills: ['Web Design', 'E-commerce', 'Next.js', 'TypeScript', 'Responsive UI'],
    image: { src: '/images/kika.png', alt: 'Kika Maison bedding and home-textile storefront website' },
  },
];
