export const SKILLS = [
  { label: "HTML", icon: "html" },
  { label: "CSS", icon: "css" },
  { label: "JavaScript", icon: "javascript" },
  { label: "TypeScript", icon: "typescript" },
  { label: "React", icon: "react" },
  { label: "Next.js", icon: "nextjs" },
  { label: "React Native", icon: "react-native" },
  { label: "Mobile App Development", icon: "mobile-app" },
  { label: "Liquid", icon: "liquid" },
  { label: "Shopify", icon: "shopify" },
  { label: "Shopify Theme Development", icon: "shopify-theme" },
  { label: "Shopify App Development", icon: "shopify-app" },
  { label: "Python", icon: "python" },
  { label: "PHP", icon: "php" },
  { label: "UI/UX Design", icon: "ui-ux" },
  { label: "Web Design", icon: "web-design" },
  { label: "Figma", icon: "figma" },
  { label: "Graphic Design", icon: "graphic-design" },
  { label: "Digital Illustration", icon: "digital-illustration" },
  { label: "Drawing", icon: "drawing" },
  { label: "2D Art", icon: "2d-art" },
  { label: "Blender", icon: "blender" },
  { label: "3D Modeling", icon: "3d-modeling" },
  { label: "Product Rendering", icon: "product-rendering" },
  { label: "Image Processing", icon: "image-processing" },
  { label: "Satellite Image Processing", icon: "satellite-image" },
  { label: "Microsoft Word", icon: "word" },
  { label: "PowerPoint", icon: "powerpoint" },
  { label: "Excel", icon: "excel" },
] as const;
